Further simplify code with err() function

diff --git a/avahi-ps b/avahi-ps
--- a/avahi-ps
+++ b/avahi-ps
@@ -26,6 +26,11 @@ EOF
 	exit 0
 }
 
+err() {
+    echo ERROR: "$@"
+    exit 1
+}
+
 filepath() {
 	local _dir="$(dirname "$0")"
 	echo $(cd "$_dir" && pwd)
@@ -72,32 +77,17 @@ NODENAME=$(uname -n)
 
 # Load plugins.
 # Errors
-if [[ ! -f ${PLUG_DIR}${FILENAME}${ERRORS_PLUG} ]]
-then
-	echo "Error, don't exist '${PLUG_DIR}${FILENAME}${ERRORS_PLUG}' plugs."
-	exit
-fi
+[[ -f ${PLUG_DIR}${FILENAME}${ERRORS_PLUG} ]] || err "${PLUG_DIR}${FILENAME}${ERRORS_PLUG} doesn't exist!"
 . ${PLUG_DIR}${FILENAME}${ERRORS_PLUG}
 
 # Execution
-if [[ ! -f ${PLUG_DIR}${FILENAME}${EXECUTE_IN} ]]
-then
-	echo "Error, don't exist '${PLUG_DIR}${FILENAME}${EXECUTE_IN}' plugs."
-	exit
-fi
+[[ -f ${PLUG_DIR}${FILENAME}${EXECUTE_IN} ]] || err "${PLUG_DIR}${FILENAME}${EXECUTE_IN} doesn't exist!"
 . ${PLUG_DIR}${FILENAME}${EXECUTE_IN}
 
-if [[ -f ${PLUG_DIR}${FILENAME}${SAVE_SERVICE} ]]
-	then
-	. ${PLUG_DIR}${FILENAME}${SAVE_SERVICE}
-fi
+[[ -f ${PLUG_DIR}${FILENAME}${SAVE_SERVICE} ]] && . ${PLUG_DIR}${FILENAME}${SAVE_SERVICE}
 
 # Database
-if [[ ! -f ${PLUG_DIR}${FILENAME}${DATABASE} ]]
-then
-	echo "Error, don't exist '${PLUG_DIR}${FILENAME}${DATABASE}' plugs."
-	exit
-fi
+[[ -f ${PLUG_DIR}${FILENAME}${DATABASE} ]] || err "${PLUG_DIR}${FILENAME}${DATABASE} doesn't exist!"
 . ${PLUG_DIR}${FILENAME}${DATABASE}
 
 # Publish
